name = "DifferentiableKernelFunctions"
uuid = "d29d353d-a6f4-4f73-b109-ea41cd8d23b2"
authors = ["Felix Benning <felix.benning@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
